- name: installing supervisor
  pip: name=supervisor
       version={{ supervisor_version }}
       virtualenv={{ supervisor_virtualenv }}
       {% if pip_args %} extra_args={{ pip_args }} {% endif %}

- name: ensuring supervisor directories
  file: path={{ supervisor_home }}/{{ item }}
        state=directory
  with_items:
    - conf.d
    - logs

- name: installing supervisor configuration
  template: src=supervisord.conf.j2
            dest={{ supervisor_config }}

- name: running supervisord
  shell: creates={{ supervisor_home }}/supervisord.pid
         chdir={{ supervisor_home }}
         {{ supervisord_path }} -c {{ supervisor_config }}

- name: installing supervisor aliases
  lineinfile: dest={{ alias_file }}
              regexp="{{ item.regexp }}"
              line="{{ item.line }}"
              create=yes
  with_items:
    - regexp: ^alias supervisord
      line: alias supervisord='{{ supervisord_path }} -c {{ supervisor_config }}'
    - regexp: ^alias supervisorctl
      line: alias supervisorctl='{{ supervisorctl_path }} -c {{ supervisor_config }}'

